export const blogsData = [
{
    id:1,
    title:"html",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur."
},
{
    id:2,
    title:"css",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur."
},
{
    id:3,
    title:"javascript",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur."
},
{
    id:4,
    title:"react",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo, sunt magni hic voluptates atque accusantium, perspiciatis expedita quibusdam ex nam quae! Ipsam deserunt delectus eveniet et non quas natus sint, ad recusandae in similique quae quos laudantium eligendi facere adipisci temporibus ex. Eum unde expedita tempora nesciunt ducimus ipsum repudiandae libero aspernatur."
}
]

